# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Modelsim_Vivado/lab11_button_process_unit/vivado/button_process_unit.cache/wt [current_project]
set_property parent.project_path E:/Modelsim_Vivado/lab11_button_process_unit/vivado/button_process_unit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Modelsim_Vivado/lab11_button_process_unit/vivado/button_process_unit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/Modelsim_Vivado/lab11_button_process_unit/src/PulseWidth_conver.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/contorler.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/counter_n.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/debouncer.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/dffer.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/dffer_en.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/synchronizer.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/timer.v
  E:/Modelsim_Vivado/lab11_button_process_unit/src/button_process_unit.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Modelsim_Vivado/lab11_button_process_unit/vivado/button_process_unit.srcs/constrs_1/new/button_process_unit.xdc
set_property used_in_implementation false [get_files E:/Modelsim_Vivado/lab11_button_process_unit/vivado/button_process_unit.srcs/constrs_1/new/button_process_unit.xdc]


synth_design -top button_unit -part xc7a35tcpg236-1


write_checkpoint -force -noxdef button_unit.dcp

catch { report_utilization -file button_unit_utilization_synth.rpt -pb button_unit_utilization_synth.pb }
